# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(282325)
$foreground = rgb(EED6D0)
$color0 = rgb(4F494B)
$color1 = rgb(231531)
$color2 = rgb(271736)
$color3 = rgb(24226A)
$color4 = rgb(5E366E)
$color5 = rgb(663B76)
$color6 = rgb(9A675A)
$color7 = rgb(DEBCB3)
$color8 = rgb(9B837D)
$color9 = rgb(2E1C42)
$color10 = rgb(341F48)
$color11 = rgb(302D8E)
$color12 = rgb(7D4992)
$color13 = rgb(884F9E)
$color14 = rgb(CE8978)
$color15 = rgb(DEBCB3)
