-- ==================================================
--  KoolDots (2026)
--  Project URL: https://github.com/LinuxBeginnings
--  License: GNU GPLv3
--  SPDX-License-Identifier: GPL-3.0-or-later
-- ==================================================
-- Auto-generated by scripts/migrate-hypr-to-lua.sh.
-- Loads split system/user Lua files from ${XDG_CONFIG_HOME:-$HOME/.config}/hypr/configs and ${XDG_CONFIG_HOME:-$HOME/.config}/hypr/UserConfigs.
local configHome = os.getenv("XDG_CONFIG_HOME") or ((os.getenv("HOME") or "") .. "/.config")
local hyprDir = configHome .. "/hypr"
local systemDir = hyprDir .. "/configs"
local userDir = configHome .. "/hypr/UserConfigs"

local function load_optional(path)
  local ok, err = pcall(dofile, path)
  if ok then
    return true
  end
  if err and tostring(err):find("No such file or directory", 1, true) ~= nil then
    return false
  end
  print("[WARN] Unable to load user override file " .. path .. ": " .. tostring(err))
  return false
end

local system_files = {
  "system_env.lua",
  "system_startup.lua",
  "system_window_rules.lua",
  "system_layer_rules.lua",
  "system_keybinds.lua",
  "system_settings.lua",
  "system_laptops.lua",
}
for _, file in ipairs(system_files) do
  local primary = systemDir .. "/" .. file
  local legacy = userDir .. "/" .. file
  if not load_optional(primary) then
    load_optional(legacy)
  end
end
local loaded_user_split = false

local user_files = {
  "user_env.lua",
  "user_startup.lua",
  "user_window_rules.lua",
  "user_layer_rules.lua",
  "user_keybinds.lua",
  "user_settings.lua",
  "user_decorations.lua",
  "user_animations.lua",
  "user_laptops.lua",
}
for _, file in ipairs(user_files) do
  local path = userDir .. "/" .. file
  if load_optional(path) then
    loaded_user_split = true
  end
end
if not loaded_user_split then
  load_optional(userDir .. "/user_overrides.lua") -- backward compatibility with older single-file overrides
end
