# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #EED6D0
background         #282325
cursor             #917A8C

active_tab_foreground     #282325
active_tab_background     #EED6D0
inactive_tab_foreground   #EED6D0
inactive_tab_background   #282325

active_border_color   #EED6D0
inactive_border_color #282325
bell_border_color     #231531

color0      #4F494B
color1		#231531
color2		#271736
color3		#24226A
color4		#5E366E
color5		#663B76
color6		#9A675A
color7		#DEBCB3
color8		#9B837D
color9		#2E1C42
color10		#341F48
color11		#302D8E
color12		#7D4992
color13		#884F9E
color14		#CE8978
color15		#DEBCB3
