# ==================================================
#  KoolDots (2026)
#  Project URL: https://github.com/LinuxBeginnings
#  License: GNU GPLv3
#  SPDX-License-Identifier: GPL-3.0-or-later
# ==================================================
# See https://wiki.hyprland.org/Configuring/Keywords/ for more variable settings
# These configs are mostly for laptops. This is addemdum to Keybinds.conf

$mainMod = SUPER
$scriptsDir = $HOME/.config/hypr/scripts
$UserConfigs = $HOME/.config/hypr/UserConfigs

# for disabling Touchpad. hyprctl devices to get device name. 
$Touchpad_Device=asue1209:00-04f3:319f-touchpad

bindeld = , xf86KbdBrightnessDown, Decrease keyboard brightness, exec, $scriptsDir/BrightnessKbd.sh --dec
bindeld = , xf86KbdBrightnessUp, Increase keyboard brightness, exec, $scriptsDir/BrightnessKbd.sh --inc
bindd = , xf86Launch1, ASUS Armory crate button, exec, rog-control-center
bindd = , xf86Launch3, Switch keyboard RGB profile, exec, asusctl led-mode -n
bindd = , xf86Launch4, Change fan profiles, exec, asusctl profile -n
bindeld = , xf86MonBrightnessDown, Decrease monitor brightness, exec, $scriptsDir/Brightness.sh --dec
bindeld = , xf86MonBrightnessUp, Increase monitor brightness, exec, $scriptsDir/Brightness.sh --inc
bindd = , xf86TouchpadToggle, Toggle touchpad, exec, $scriptsDir/TouchPad.sh

# Screenshot keybindings using F6 (no PrinSrc button)
bind = $mainMod, F6, exec, $scriptsDir/ScreenShot.sh --now # screenshot
bind = $mainMod SHIFT, F6, exec, $scriptsDir/ScreenShot.sh --area # screenshot (area)
bind = $mainMod CTRL, F6, exec, $scriptsDir/ScreenShot.sh --in5 # # screenshot (5 secs delay)
bind = $mainMod ALT, F6, exec, $scriptsDir/ScreenShot.sh --in10 # screenshot (10 secs delay)
bind = ALT, F6, exec, $scriptsDir/ScreenShot.sh --active # screenshot (active window only)

$TOUCHPAD_ENABLED = true
device {
  name = $Touchpad_Device
  enabled = $TOUCHPAD_ENABLED
}

